name: CI

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev ninja-build
      - name: Download and extract
        run: |
          wget -O qemu.tar.xz https://download.qemu.org/qemu-7.2.0.tar.xz
          tar xvJf qemu.tar.xz --strip-components=1

      - name: Configure
        run: ./configure --prefix=/opt/qemu

      - name: Compile
        run: make -j 16

      - name: Install
        run: sudo make install

      - name: Create tarball
        run: tar zcvf qemu-compiled.tar.gz /opt/qemu

      - uses: actions/upload-artifact@v3
        with:
          name: compiled-version
          path: qemu-compiled.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: qemu-compiled.tar.gz
